"""Auto migration

Revision ID: c2766e558f6f
Revises: 
Create Date: 2025-08-28 04:49:17.913802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2766e558f6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('source_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key of the source URL'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='URL link that needs to be parsed'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Title/name for this URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description for the URL'),
    sa.Column('redirected_url', sa.String(length=2048), nullable=True, comment='Final URL after redirects (if different from original URL)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_source_urls_id'), 'source_urls', ['id'], unique=False)
    op.create_table('source_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key of the source content'),
    sa.Column('source_url_id', sa.Integer(), nullable=False, comment='Foreign key to source_urls table'),
    sa.Column('content', sa.Text(), nullable=False, comment='Parsed text content from the URL'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Title extracted from the URL content'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description or summary extracted from the URL'),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True, comment='Metadata about the extraction process (e.g., method, settings, stats)'),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this content was parsed and saved'),
    sa.ForeignKeyConstraint(['source_url_id'], ['source_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_content_id'), 'source_content', ['id'], unique=False)
    op.create_index(op.f('ix_source_content_source_url_id'), 'source_content', ['source_url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_content_source_url_id'), table_name='source_content')
    op.drop_index(op.f('ix_source_content_id'), table_name='source_content')
    op.drop_table('source_content')
    op.drop_index(op.f('ix_source_urls_id'), table_name='source_urls')
    op.drop_table('source_urls')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
